Repository jni-rs/jni-rs, pull requests merged in 2018-10, with the labels that each got.

#139 Fixed the issue with early detaching of a thread by nested AttachGuard.
  CHANGELOG.md
  src/wrapper/java_vm/vm.rs
  tests/vm.rs
Labels: Next to merge :flight_arrival:

#135 Fix (some) clippy issues
  CHANGELOG.md
  src/wrapper/jnienv.rs
  src/wrapper/objects/global_ref.rs
  src/wrapper/signature.rs
  src/wrapper/strings/ffi_str.rs
Labels: Next to merge :flight_arrival:, breaking

#136 Macro usage enhancements
  CHANGELOG.md
  src/wrapper/jnienv.rs
  tests/jni_api.rs
Labels: breaking

#145 Implemented Sync for GlobalRef
  CHANGELOG.md
  src/wrapper/objects/global_ref.rs
Labels: Next to merge :flight_arrival:, breaking

#143 Added appveyor
  .appveyor.yml
Labels: Next to merge :flight_arrival:

#147 Implemented Clone for JNIEnv.
  CHANGELOG.md
  src/wrapper/jnienv.rs
Labels: breaking

#140 Unify low level APIs [ECR-2356]
  CHANGELOG.md
  benches/api_calls.rs
  src/wrapper/jnienv.rs
  src/wrapper/macros.rs
  src/wrapper/objects/global_ref.rs
  src/wrapper/objects/jlist.rs
  src/wrapper/objects/jmap.rs
  src/wrapper/strings/java_str.rs
  tests/jni_api.rs
Labels: breaking
